PART 1
class Cooking_Lasngya{
    public class Lasngna {
  final int mintues = 40;
  public expectedbakingintheoven(){
  return mintues;
  }//PART 2
  public int reamaniningminutesinoven(int minutespast){
    return lefttoverminute = 40-minutespast
  }
  public int preperationtimeinminutes(){
    return layers = 2
  }//Part 3
  public int totaltimeinminutes(int minutesinoven, int layers){
    return minutesinoven + layers
  }

    }
}